version: '3.8'

services:
  app:
    build: .
    container_name: portfolio_app
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "127.0.0.1:8000:8000" # Expuesto solo localmente por seguridad
    volumes:
      - ./app:/app/app