version: '3.8'

services:
  app:
    build: .
    container_name: portfolio_app
    restart: always
    # Uvicorn escucha internamente en el 8000
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      # Ubuntu recibe en el 8001 -> Lo manda al 8000 del contenedor
      - "8001:8000"
    volumes:
      - ./app:/app/app